name: actions
on: [push]
jobs:
  client:
    name: make print
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: print push
        run: echo push created
        
      - name: run project
        run: npm run build
